spring:
    application:
        name: Web Gestao

    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/webgestao}
        username: ${SPRING_DATASOURCE_USERNAME:devuser}
        password: ${SPRING_DATASOURCE_PASSWORD:devpass}
        driver-class-name: org.postgresql.Driver

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

    flyway:
        enabled: true
        locations: classpath:db/migration
        baseline-version: 1.0.0

    cloud:
        openfeign:
            client:
                config:
                    location-iq-api:
                        url: ${LOCATION_IQ_API_URL:test}

api:
    api-keys:
        location-iq-api-key: ${LOCATION_IQ_API_KEY:test}
