spring:
    application:
        name: Web Gestao

    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/webgestao}
        username: ${SPRING_DATASOURCE_USERNAME:devuser}
        password: ${SPRING_DATASOURCE_PASSWORD:devpass}
        driver-class-name: org.postgresql.Driver

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

    flyway:
        enabled: true
        locations: classpath:db/migration
        baseline-version: 1.0.0

    cloud:
        openfeign:
            client:
                config:
                    location-iq-api:
                        url: ${LOCATION_IQ_API_URL:test}
                        error-decoder: com.xpronto.webgestao.infrastructure.config.integrations.IntegrationsErrorDecoder

    mail:
        host: ${MAIL_HOST:localhost}
        port: ${MAIL_PORT:8080}
        username: ${MAIL_USERNAME:test}
        password: ${MAIL_PASSWORD:test}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

api:
    client-url: ${CLIENT_URL:http://localhost:3000}
    api-keys:
        location-iq-api-key: ${LOCATION_IQ_API_KEY:test}
        web-gestao-api-key: ${API_KEY:dev-test-key}
    jwt:
        access-token:
            secret: ${JWT_ACCESS_TOKEN_SECRET:access-secret}
            expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:15}
        refresh-token:
            secret: ${JWT_REFRESH_TOKEN_SECRET:refresh-secret}
            expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:7}
        invite-token:
            secret: ${JWT_INVITE_TOKEN_SECRET:invite-secret}
            expiration: ${JWT_INVITE_TOKEN_EXPIRATION:10}
